### PR TITLE
Overkill damage

### LINKED ISSUE #47: Make use of "overkillDamage" stat on the web side
A recent ss commit adds the "overkillDamage" stat which counts the amount of damage that was done to a player past their health on death. For example, if the victim's health before death was 3, and a 5 shot damage was fired at the victim, "overkillDamage" would be incremented by 2.

A total damage stat can be calculated by doing totalDmg = "damagedone" + "overkillDamage". This totalDmg value should be equal to the damage value that is displayed on logstf currently.

Implementation on the web server side is needed to take advantage of this stat.

https://github.com/SizzlingStats/sizzlingplugins/commit/0db12fd3b2a0bd979303283b91966270a11347ab

### PR DESCRIPTION
**Pull request by forivall**
fixes #47 

Note the terminology change. A FAQ page has been added to explain the difference.

Some other minor changes were made, mainly in comments.

A full test, with a server running an up-to-date stats plugin, will be needed. [ngrok](https://ngrok.com/) works well for this; we should make a note of that. @dy-dx , did you use anything like it?

### CODE REVIEW

**Comment by forivall** [comment]
currently publicly visible at http://0350a0a5.ngrok.io/stats/4

**Comment by dy-dx** [comment]
Thanks. I will test this out tonight.

**Comment by SizzlingCalamari** [comment]
The plan for the terminology now is
"RD" - "Real Damage"
"TD" - "Total Damage"
"RDPM" - "Real Damage Per Minute"
"TDPM" - "Total Damage Per Minute"

I'm fine with keeping the faq page to explain those stats just in case. (I get ss vs logs damage questions very frequently)

**Comment by SizzlingCalamari** [comment]
LGTM

**Comment by dy-dx** [comment]
@SizzlingCalamari @forivall deployed

**Comment by forivall** [comment]
Hmm, maybe the FAQ could be updated (in the short term) that that users will need to update the sizzling stats plugin to see that they are different

or, i could submit a pr to check the version and only display the tdpm / td columns if the plugin version is high enough. @SizzlingCalamari is the old version v0.1 and the new version v0.2?

**Comment by SizzlingCalamari** [comment]
@forivall 
We were just planning on doing a rollback until the plugin is ready, but adding the version number check sounds good to keep past stats looking the same. The current header version before this change is v0.2. I forgot to change the version when updating the json structure in the plugin, so v0.3 will be the version containing the overkill damage stat.

**Comment by forivall** [comment]
:+1:

**Pull request merged**
